'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class EN
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Contratacion.Contrato.Web.EN", GetType(EN).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Contract.
        '''</summary>
        Friend Shared ReadOnly Property lblLegendCtrContrato() As String
            Get
                Return ResourceManager.GetString("lblLegendCtrContrato", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCtrCodContrato() As String
            Get
                Return ResourceManager.GetString("lblCtrCodContrato", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCodContratoAsociado() As String
            Get
                Return ResourceManager.GetString("lblCodContratoAsociado", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblContratoSAP() As String
            Get
                Return ResourceManager.GetString("lblContratoSAP", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCtrEstadoContrato() As String
            Get
                Return ResourceManager.GetString("lblCtrEstadoContrato", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCtrFecTerminado() As String
            Get
                Return ResourceManager.GetString("lblCtrFecTerminado", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCtrFecEstadoContrato() As String
            Get
                Return ResourceManager.GetString("lblCtrFecEstadoContrato", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCtrFecFirma1() As String
            Get
                Return ResourceManager.GetString("lblCtrFecFirma1", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblEstadoPresupuesto() As String
            Get
                Return ResourceManager.GetString("lblEstadoPresupuesto", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCtrFecEstadoPresupuesto() As String
            Get
                Return ResourceManager.GetString("lblCtrFecEstadoPresupuesto", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblImporteTotalContrato() As String
            Get
                Return ResourceManager.GetString("lblImporteTotalContrato", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblTipoContrato() As String
            Get
                Return ResourceManager.GetString("lblTipoContrato", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblidioma() As String
            Get
                Return ResourceManager.GetString("lblidioma", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblEstadoDocumento() As String
            Get
                Return ResourceManager.GetString("lblEstadoDocumento", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCtrFecGeneracion() As String
            Get
                Return ResourceManager.GetString("lblCtrFecGeneracion", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCtrVersionDocumento() As String
            Get
                Return ResourceManager.GetString("lblCtrVersionDocumento", resourceCulture)
            End Get
        End Property

        Friend Shared ReadOnly Property lblCtrCodPresupuesto() As String
            Get
                Return ResourceManager.GetString("lblCtrCodPresupuesto", resourceCulture)
            End Get
        End Property
Friend Shared ReadOnly Property lblRazonSocial1() As String
    Get
        Return ResourceManager.GetString("lblRazonSocial1", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblCentGest() As String
    Get
        Return ResourceManager.GetString("lblCentGest", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblPersonaAlta() As String
    Get
        Return ResourceManager.GetString("lblPersonaAlta", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblObservaciones() As String
    Get
        Return ResourceManager.GetString("lblObservaciones", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblObservacionesTec() As String
    Get
        Return ResourceManager.GetString("lblObservacionesTec", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblObservacionesMed() As String
    Get
        Return ResourceManager.GetString("lblObservacionesMed", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblHorasPerfilesMedycsa() As String
    Get
        Return ResourceManager.GetString("lblHorasPerfilesMedycsa", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblAltaGrupoCliente() As String
    Get
        Return ResourceManager.GetString("lblAltaGrupoCliente", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblCeco() As String
    Get
        Return ResourceManager.GetString("lblCeco", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblLineaNegocio() As String
    Get
        Return ResourceManager.GetString("lblLineaNegocio", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblGestor() As String
    Get
        Return ResourceManager.GetString("lblGestor", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblDesdeContrato() As String
    Get
        Return ResourceManager.GetString("lblDesdeContrato", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblListadoContratos() As String
    Get
        Return ResourceManager.GetString("lblListadoContratos", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblLegendDesdeContrato() As String
    Get
        Return ResourceManager.GetString("lblLegendDesdeContrato", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblMigrarContactos() As String
    Get
        Return ResourceManager.GetString("lblMigrarContactos", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblMigrarFirmantesCliente() As String
    Get
        Return ResourceManager.GetString("lblMigrarFirmantesCliente", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblMigrarFirmantesSPFM() As String
    Get
        Return ResourceManager.GetString("lblMigrarFirmantesSPFM", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblLegendDatosCliente() As String
    Get
        Return ResourceManager.GetString("lblLegendDatosCliente", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblRazonSocial() As String
    Get
        Return ResourceManager.GetString("lblRazonSocial", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblActividad() As String
    Get
        Return ResourceManager.GetString("lblActividad", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblDomicilioSocial() As String
    Get
        Return ResourceManager.GetString("lblDomicilioSocial", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblGrabarDomiSocial() As String
    Get
        Return ResourceManager.GetString("lblGrabarDomiSocial", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblAltaNombreCompletoSocial() As String
    Get
        Return ResourceManager.GetString("lblAltaNombreCompletoSocial", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblAltaNombreSocial() As String
    Get
        Return ResourceManager.GetString("lblAltaNombreSocial", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblAltaApellido1Social() As String
    Get
        Return ResourceManager.GetString("lblAltaApellido1Social", resourceCulture)
    End Get
End Property

Friend Shared ReadOnly Property lblAltaApellido2Social() As String
    Get
        Return ResourceManager.GetString("lblAltaApellido2Social", resourceCulture)
    End Get
End Property

    End Class
End Namespace
